const { buildSchema } = require('graphql')

const schema = buildSchema(`
    type Query {
        allUsers: [User!]
    }

    type Mutation {
        createUser(name: String!, email: String!): User
        deleteByEmail(email: String!): String!
        updateOne(email: String!, name: String): User
    }

    type User {
        _id: ID
        name: String
        email: String
    }
`)

module.exports = schema